"""
Contenido de limpiezas-planeadas.xlsx: qué estamos asumiendo y qué vamos a limpiar en los datos.

ESTE es el archivo que se edita; el Excel se genera con:

    uv run --no-project --with openpyxl python tools/limpiezas/generar.py

Cada pestaña es un dict con su nombre, el ancho de cada columna, los encabezados y las filas.
Una celda es un valor (texto o número) o, si lleva estilo, Celda(valor, negrita=True, relleno="verde").
Una fila [] es un renglón vacío, para separar secciones.
En "Resumen", la columna Estado se colorea sola según su valor (ver ESTADOS en generar.py).
"""
from celda import Celda

HOJAS = [
    {
        "nombre": 'Resumen',
        "anchos": [4.0, 11.0, 24.0, 34.0, 15.0, 44.0, 40.0, 20.0],
        "encabezados": ['#', 'Familia', 'Hoja', 'Qué se limpia', 'Celdas o columnas', 'Por qué', 'Qué pasa si NO se hace', 'Estado'],
        "filas": [
            [
                1,
                'Vehículos',
                'VEHICULOS',
                'Vaciar los centinelas de 13 columnas de datos',
                '1,124 celdas',
                "Al dar de baja una unidad se escribe 'BAJA VEHICULAR' DENTRO de columnas de datos: SEDE 309, UBICACION 309, DEPARTAMENTO 139, RESPONSABLE VEHICULO 125, PLACA 84, COLOR 69 y 7 más. No son datos, son estatus.",
                'La sincronización copia esa palabra encima del dato bueno de los otros módulos. Hoy lo frena la guarda CENTINELAS, pero es una curita.',
                'PENDIENTE',
            ],
            [
                2,
                'Vehículos',
                'VEHICULOS',
                'DEPARTAMENTO de las unidades dadas de baja: rellenar 8, vaciar 115',
                '123 celdas',
                "Las 123 filas con DEPARTAMENTO='BAJA VEHICULAR' tienen las 123 también ESTATUS='BAJA VEHICULAR', así que la baja NO se pierde. De esas, 8 tienen su área recuperable desde HOLOGRAMAS o INSPECCION VEHICULAR, y las fuentes coinciden en las 8.",
                'DEPARTAMENTO sigue mintiendo en 19% de la flota y el catálogo no sirve para reportes por área.',
                'PENDIENTE',
            ],
            [
                3,
                'Vehículos',
                'DEPARTAMENTOS',
                'Dar de alta OOAM TECNICO y OOAM ADMINISTRATIVO',
                '2 filas nuevas',
                'Son áreas REALES de 25 vehículos activos (18 y 7), confirmado por Ayrton. El catálogo está desactualizado y no las tiene.',
                'Cualquier validación contra el catálogo rechaza datos buenos. Ya pasó: un primer cálculo de la limpieza #2 dio 7 y 116 en vez de 8 y 115 por validar contra él.',
                'PENDIENTE',
            ],
            [
                4,
                'Líneas',
                'LINEAS TELEFONICAS',
                'Borrar 15 columnas completamente vacías',
                '15 columnas',
                'SEGUNDO, TERCER, CUARTO y QUINTO RESPONSABLE, cada uno con su NOMBRE y PUESTO: 0 filas con dato en las 15. Solo se usan RESPONSABLE (100%) y NOMBRE QUIEN USA (11%). || 30/09/2026: hay que volver a medirlo. LINEAS TELEFONICAS paso de 56 a 58 columnas en la reestructuracion, asi que el juego de columnas vacias cambio.',
                '56 columnas de las que 15 son ruido; nadie sabe si se deben llenar.',
                'RE-MEDIR',
            ],
            [
                5,
                'Líneas',
                'LINEAS TELEFONICAS',
                'Arreglar la columna cuyo encabezado dice #REF!',
                '1 encabezado',
                'Entre PUESTO QUINTO RESPONSABLE y PUESTO RESPONSABLES 2. En el libro de pruebas alguien ya la reparó como NOMBRE RESPONSABLES 2; en producción sigue rota. || 30/09/2026: YA ESTA HECHO. Emmanuel la reparo en el libro compartido: ahora se llama NOMBRE RESPONSABLES 2. Falta aplicarlo en produccion.',
                'Una columna sin nombre usable, y el error se arrastra a cualquier copia del libro.',
                'HECHO',
            ],
            [
                6,
                'Líneas',
                'LINEAS TELEFONICAS',
                'Vaciar centinelas de NUMERO TELEFONO e IMEI',
                '684 celdas',
                "NUMERO TELEFONO='NO APLICA' en 638 filas (son equipos SIN línea) e IMEI con 'N/A' x25, 'TELCEL' x10, '0' x6, 'SOLO LINEA' x3, 'NA' x2. || 30/09/2026: sigue valiendo. LINEAS TELEFONICAS no se elimino, y NUCO sigue siendo llave unica (1,615 de 1,615) despues de la reestructuracion.",
                "Ni el número ni el IMEI sirven para emparejar, y 'NO APLICA' aparece 638 veces como si fuera un número de teléfono.",
                'EN PAUSA',
            ],
            [
                7,
                'Líneas',
                'REACTIVACION / SOLICITUD / BITACORA DE DESECHO',
                'Rellenar ID LINEA por cascada IMEI → SIM → número',
                '735 celdas',
                'Esas 3 hojas NO tienen ningún vínculo con la línea: su FOLIO es un consecutivo propio (1, 2, 3, 4…). Por cascada emparejan: Desecho 228/228 (100%), Solicitud 206/229 (90%), Reactivación 301/361 (83%). El IMEI va primero porque nunca cambia y no tiene duplicados. || 30/09/2026: YA NO APLICA. Las tres hojas -REACTIVACION DE LINEAS, SOLICITUD DE LINEAS y BITACORA DE DESECHO- se ELIMINARON en la reestructuracion de Lineas. No implementar la cascada.',
                'Tres hojas huérfanas del padre. No se puede saber qué línea se reactivó ni qué equipo se desechó sin cruzar a mano.',
                'YA NO APLICA',
            ],
            [
                8,
                'Líneas',
                'LINEAS TELEFONICAS',
                'Resolver el padre borrado EEBA06A3',
                '25 filas hijas',
                'Ese ID no existe en la hoja madre y le apuntan 3 inspecciones, 4 responsivas y 18 cambios. || 30/09/2026: hay que volver a medirlo. Las hijas perdieron filas -CAMBIOS LINEAS TELEFONICAS -1,961, INSPECCIONES LINEAS -170, RESPONSIVAS LINEAS -133- asi que los 25 hijos huerfanos de EEBA06A3 ya no son 25.',
                '25 registros apuntan a una línea que ya no existe.',
                'RE-MEDIR',
            ],
            [
                9,
                'Caja Chica',
                'CAJAS CHICAS',
                'Decidir qué hacer con CALIFICACION PROMEDIO',
                '1 columna',
                '0 de 285 filas con dato, mientras que ARQUEOS.CALIFICACION_AUDITORIA_FINAL está llena en 145 de 145. O se calcula (promedio de sus arqueos) o se borra.',
                'Una columna que promete un dato y nunca lo da.',
                'DECISION DE NEGOCIO',
            ],
            [
                10,
                'Caja Chica',
                'ARQUEOS',
                'Borrar 4 columnas completamente vacías',
                '4 columnas',
                'TIEMPO DE ARQUEO, CANTIDAD M, CANTIDAD B y FIRMA ASISTENTE: 0 de 145 con dato. CANTIDAD M y CANTIDAD B llaman la atención porque TOTAL M y TOTAL B sí están llenas.',
                '79 columnas de las que 4 son ruido.',
                'PENDIENTE',
            ],
            [
                11,
                'Caja Chica',
                'CAJAS CHICAS',
                'Unificar el vocabulario de DEPARTAMENTO',
                '25 celdas',
                "25 de 283 no están en el catálogo DEPARTAMENTOS. Dos son el MISMO departamento escrito distinto: 'CAPITAL HUMANO/ADMON OFICINAS' y 'CAPITAL HUMANO /ADMON OFICINA' (un espacio y un plural). Y reaparecen OOAM TECNICO y OOAM ADMINISTRATIVO.",
                'Agrupar gasto por departamento da dos renglones para la misma área.',
                'PENDIENTE',
            ],
            [
                12,
                'Caja Chica',
                'ARQUEOS',
                'Revisar el arqueo 2026_222_001',
                '1 celda',
                'Su DIFERENCIA dice -2.50 pero TOTAL GENERAL - MONTO CAJA da +2.50: el signo está invertido. Es el ÚNICO de los 145 que no cuadra.',
                'Un faltante reportado que en realidad es un sobrante.',
                'PENDIENTE',
            ],
            [
                13,
                'Caja Chica',
                'CAJAS CHICAS',
                'Cerrar o reasignar 2 cajas VIGENTES de gente dada de baja',
                '2 cajas, $20,000',
                'CCH 250 a nombre de ANA ITZEL PEREZ LOPEZ, dada de baja el 01/11/2023 (hace casi 3 años), con $10,000. Y CCH 254 de JOCELYN ALVAREZ FRANCO, baja el 21/09/2026, con $10,000. Las dos siguen en ESTATUS=VIGENTE.',
                'Dos fondos activos de $10,000 cada uno a nombre de personas que ya no trabajan aquí. De todo lo que salió hoy, esto es lo más urgente.',
                'URGENTE',
            ],
            [
                14,
                'Caja Chica',
                'CAJAS CHICAS',
                'Corregir el encabezado JEFE INMEDIATO DEL REPSONSABLE',
                '1 encabezado',
                'Dice REPSONSABLE en vez de RESPONSABLE. Es una columna real y con datos (223 de 285).',
                'Cualquier código que la busque por nombre tiene que escribir el error a propósito, y el que la escriba bien no la encuentra.',
                'PENDIENTE',
            ],
            [
                15,
                'Caja Chica',
                'ARQUEOS',
                'Que el sistema nuevo derive los totales, por robustez',
                '2 columnas',
                "ARQUEOS cuadra al centavo en los 145 (ver 'Caja Chica — el dinero'), así que esto YA NO es un defecto. Pero en la hoja no hay una sola fórmula: TOTAL GENERAL y DIFERENCIA son literales que escribió AppSheet. Nada impide que un día lleguen mal.",
                'Nada roto hoy. Es una mejora: si el sistema nuevo los calcula desde el desglose, la inconsistencia se vuelve imposible en vez de depender de que quien escriba lo haga bien.',
                'PENDIENTE',
            ],
            [
                16,
                'Caja Chica',
                'CAJAS CHICAS',
                'Agregar la llave de la PERSONA responsable',
                '1 columna, 283 filas',
                'Es la unica referencia que falta en la familia: CAJAS CHICAS no tiene No EMPLEADO, solo el nombre y el correo. Se puede rellenar: 283 de 285 (99%) emparejan con COLABORADORES ACTUALIZADO por correo (76%) o por nombre (97%).',
                'Sin ella no hay forma automatica de saber que una caja VIGENTE esta a nombre de alguien dado de baja. Las dos de la limpieza #13 se encontraron a mano.',
                'PENDIENTE',
            ],
            [
                '17',
                'Vehículos',
                'HOLOGRAMAS',
                'Quitar el guión bajo inicial de 13 series de SERIE VEHICULO',
                '13 celdas',
                "13 series traen un '_' de más al inicio ('_VR3EC9HP2MJ503983'). Sin ese carácter, la serie SÍ existe en VEHICULOS: son el mismo vehículo, escrito mal. Es la limpieza más barata y más segura de toda la lista, porque el padre se comprueba antes de tocar nada.",
                "13 hologramas se quedan sin ID VEHICULO para siempre, contados como 'vehículo personal' cuando sí están en el catálogo. La tasa de HOLOGRAMAS queda en 56% en vez de 62%, y el número engaña a quien lo lea después.",
                'PENDIENTE',
            ],
            [
                '18',
                'Vehículos',
                'HOLOGRAMAS',
                'Revisar 7 valores de SERIE VEHICULO que no tienen forma de VIN',
                '7 celdas',
                "Un VIN tiene 17 caracteres. Estos no: '1', '123456789', 'UYC383A' (parece una placa, no una serie), '1GNM616030' (10), 'L15A77804197' (12) y '3MDDJBTVXKM31054' (16, le falta uno). Los dos últimos se ven como dedazo recuperable; los primeros, como relleno.",
                'Quedan 7 hologramas que nunca van a emparejar con nada y que ensucian la cuenta de vehículos personales. No rompen nada, pero tampoco se pueden auditar.',
                'PENDIENTE',
            ],
            [
                19,
                'Vehículos',
                'VEHICULOS',
                'Vaciar SERIE SENSOR de los 22 vehículos cuyo sensor está en BAJA',
                '22 celdas',
                'Al dar de baja un sensor nadie limpiaba VEHICULOS. Medido en producción el 01/10/2026: los 22 son reales (los mismos en el libro del equipo), no datos de prueba. Decisión de Ayrton (01/10/2026): al dar de baja, se vacía. Desde ahora INSTALACION DE SENSORES es la dueña de SERIE SENSOR y SENSOR en VEHICULOS (al revés de las demás columnas, donde VEHICULOS es la dueña).',
                'VEHICULOS sigue mostrando como instalada la serie de un sensor que ya se retiró.',
                'PENDIENTE',
            ],
            [
                20,
                'Vehículos',
                'VEHICULOS',
                'Vaciar SERIE SENSOR de CTA0295 y CTA0481: tienen serie pero ningún renglón de sensor',
                '2 celdas',
                'Sus series (G95Z0ZTP77A1 y G9W5HX33RZ6H) no aparecen en INSTALACION DE SENSORES. CAVEAT: puede ser un sensor instalado que nunca se registró. Si es así, lo correcto es DAR DE ALTA el sensor, no borrar la serie. Revisarlos antes de sincronizar: la pantalla de Relaciones los lista uno por uno.',
                'Una serie que no se puede rastrear a ninguna instalación ni responsiva.',
                'PENDIENTE',
            ],
            [
                21,
                'Vehículos',
                'VEHICULOS',
                'Reducir SENSOR a dos valores: SI TIENE SENSOR / NO TIENE SENSOR',
                '39 celdas',
                'Decisión de Ayrton (01/10/2026). Se calcula del sensor: ACTIVO → SI TIENE; en BAJA o sin renglón → NO TIENE. Pasan a NO TIENE 36: CANCELADO 18, SENSOR TI 5, NO COMPATIBLE 2, NO APLICA AUTO DG 2, EN PROCESO DE INSTALACION 1, vacío 2, y 6 que dicen SI TIENE sin sensor activo. Pasan a SI TIENE 3 con sensor activo (CANCELADO 2, SENSOR TI 1). CAVEAT: se PIERDE el matiz de CANCELADO, NO COMPATIBLE, SENSOR TI, etc. — si hace falta, tendrá que vivir en otra columna. Y los 6 "SI TIENE" sin activo pueden ser sensores no registrados, igual que la limpieza #20.',
                'SENSOR dice una cosa y la hoja de sensores otra en 39 vehículos, y nadie sabe cuál creer.',
                'PENDIENTE',
            ],
            [
                22,
                'Vehículos',
                'VEHICULOS / HOLOGRAMAS / INSPECCION VEHICULAR',
                'Medir y decidir el dueño de 3 columnas que se llaman igual en VEHICULOS y en una hija',
                '3 columnas',
                'Aparecieron al revisar Sensores y NO están en el mapa de Relaciones: HOLOGRAMAS.NO ECONOMICO (no se sabe quién manda), INSPECCION VEHICULAR.POLIZA SEGURO (probablemente la póliza del día: bitácora) y VEHICULOS.VERIFICACION (SI / NO) (huele a resumen de VERIFICACIONES, como SENSOR).',
                'Pueden estar desincronizadas sin que nada lo detecte, igual que SERIE SENSOR hasta hoy.',
                'RE-MEDIR',
            ],
            [
                23,
                'Vehículos',
                'VEHICULOS',
                'Homologar el nombre de la columna UBICACION → OFICINA / DESARROLLO',
                '1 encabezado',
                'Es el mismo dato que INSTALACION DE SENSORES, INSPECCION VEHICULAR, las hojas de Líneas y los catálogos (LISTAS, DEPARTAMENTOS) llaman OFICINA / DESARROLLO; VEHICULOS era la única que le decía UBICACION, y sus opciones ya salían del catálogo OFICINA / DESARROLLO. Decisión de Ayrton (01/10/2026): homologar los nombres en toda la base, caso por caso — ver la pestaña "Nombres de columnas". Lo hace el paso "nombres" del pipeline de Vehículos (vehiculos2Escribir).',
                'El mismo dato con dos nombres: la pantalla Datos conectados tiene que explicar "en Sensores se llama…", y cualquier cruce entre hojas tiene que saber la equivalencia.',
                'PENDIENTE',
            ],
        ],
    },
    {
        "nombre": 'Lo que NO se toca',
        "anchos": [11.0, 30.0, 40.0, 52.0, 16.0],
        "encabezados": ['Familia', 'Hoja / columna', 'Parece basura porque…', 'Pero NO se limpia, porque…', 'Cuánto es'],
        "filas": [
            [
                'Vehículos',
                'INSPECCION VEHICULAR — todas sus columnas copiadas',
                '184 valores no coinciden con el catálogo de VEHICULOS',
                'Es una BITÁCORA fechada: el responsable y el área son los del día en que se hizo la inspección. Confirmado por Ayrton. Corregirlos borraría a qué área se le revisó la unidad, que es el valor de la inspección como evidencia.',
                '184 diferencias',
            ],
            [
                'Vehículos',
                'TICKETS — columna PLACA',
                '59% no empareja con ninguna placa del catálogo',
                "Un ticket puede hablar de ningún vehículo, de uno o de varios: la celda dice 'VARIAS' x119, 'VARIOS' x17, y hasta dos placas juntas ('UKR913H, ULP697K'), más 202 vacías. Representarlo requiere una tabla puente, no limpiar la columna.",
                '742 filas',
            ],
            [
                'Vehículos',
                'HOLOGRAMAS — 91 filas sin vehículo',
                '36% no empareja con el catálogo',
                "Son vehículos PERSONALES que por diseño no están en el catálogo, y ahí los datos se capturan a mano. CORRECCIÓN (30/09/2026): antes decían 111. Al medirlas después de escribir ID VEHICULO resultó que 13 traen un '_' de más y 7 no tienen forma de VIN — esas 20 SÍ se limpian, y son las limpiezas #17 y #18. Personales de verdad son 91.",
                '91 filas (antes decía 111)',
            ],
            [
                'Vehículos',
                'CAMBIOS VEHICULOS — 1,904 filas',
                '21% apunta a folios que ya no existen',
                'Es un log de auditoría: registra cambios de unidades que después se borraron. Un log que solo conserva lo que sigue vivo no sirve de log.',
                '1,904 filas',
            ],
            [
                'Líneas',
                'LINEAS TELEFONICAS — 638 filas sin número',
                "NUMERO TELEFONO dice 'NO APLICA'",
                "El VALOR 'NO APLICA' sí se limpia (limpieza #6), pero las FILAS no: son equipos sin línea, y son el 39% del inventario. TIPO='EQUIPO' lo dice. No son registros basura.",
                '638 filas',
            ],
            [
                'Líneas',
                'RESPONSIVAS LINEAS — sus columnas copiadas',
                'Muchos valores difieren del catálogo',
                'Una responsiva FIRMADA dice quién recibió qué ese día. Sincronizarla sería alterar un documento firmado.',
                'todas',
            ],
            [
                'Caja Chica',
                'CAJAS CHICAS — 186 cajas CERRADA',
                '65% de las cajas están cerradas',
                'No es basura, es historia: hay 14 arqueos sobre cajas hoy cerradas, hechos cuando estaban vigentes. Lo que toca es que la app muestre VIGENTE por omisión (97 cajas), no borrar las cerradas.',
                '186 de 285',
            ],
            [
                'Caja Chica',
                'ARQUEOS — 51 con sobrante y 10 con faltante',
                'Solo 84 de 145 arqueos cuadran exactos',
                'NO es un problema de datos: es el resultado del arqueo. TOTAL GENERAL incluye pendientes por facturar, así que un sobrante puede ser normal. Es un asunto operativo para el área, no de limpieza. El faltante mayor es -1,500.00.',
                '61 de 145',
            ],
            [
                'Todas',
                'ARQUEOS — las 17 columnas AUDIT_',
                'Son 17 columnas con nombres largos y repetitivos',
                'Están llenas las 17 en los 145 arqueos. Se usan todas.',
                '145 de 145',
            ],
            [
                'Caja Chica',
                'ARQUEOS — DIFERENCIA = 0 en 84 arqueos',
                'Parece que nadie revisa nada porque siempre cuadra',
                'Un arqueo sano se ve exactamente así, y DIFERENCIA SÍ es un control real: TOTAL GENERAL cuadra con sus 12 partes en los 145 arqueos. Una versión anterior de este archivo decía que el total no se podía comprobar; era un error de medición mío.',
                '84 de 145',
            ],
            [
                'Caja Chica',
                'ARQUEOS — TOTAL EFECTIVO = 0 en 109 arqueos',
                'Un arqueo sin una sola moneda ni billete contado',
                'El fondo de esas cajas no es efectivo: está en cuenta bancaria o fintech, y se registra en DISPONIBLE CUENTA BANCARIA (111 arqueos, $986,185.11). La hoja incluso tiene DESCRIPCION CUENTA BANCARIA y Nombre_Fintech.',
                '109 de 145',
            ],
            [
                'Caja Chica',
                'ARQUEOS — sus columnas copiadas del catalogo',
                'MONTO CAJA no coincide con el catalogo en 4 arqueos',
                'ARQUEOS es una BITACORA y sus copias estan al 97-100%: RESPONSABLE 145/145, AREA / DEPARTAMENTO 145/145, METODO REEMBOLSO 145/145, PUESTO 144/145. Los 4 MONTO CAJA distintos estan explicados los 4 por INCREMENTOS: el arqueo guardo el fondo de ESE dia y el catalogo muestra el de hoy. Sincronizar destruiria 4 registros correctos para arreglar 0 problemas.',
                '4 de 145',
            ],
            [
                'Vehículos',
                'INSTALACION DE SENSORES.TIPO DE COMBUSTIBLE y HOLOGRAMAS.RAZON SOCIAL',
                'Se llaman igual que una columna de VEHICULOS, así que parecen copias desincronizadas',
                'Significan otra cosa. En Sensores es el PRODUCTO que carga la unidad (MAGNA/PREMIUM/DIESEL) y en VEHICULOS el tipo de motor (GASOLINA/DIESEL); en Hologramas es la empresa del contrato de la tarjeta, no la dueña del vehículo. Por eso NO están en el mapa de Relaciones y nunca se sincronizan.',
                '2 columnas',
            ],
            [
                'Vehículos',
                'INSTALACION DE SENSORES → VEHICULOS: un solo renglón de sensor por vehículo',
                'Una sincronización "simple" podría tener que escoger entre varios sensores de la misma unidad',
                'Hoy no hace falta escoger: en producción cada vehículo tiene a lo más un renglón de sensor (208 de 208). Es una SUPOSICIÓN medida, no una regla del sistema: si algún día una unidad tiene dos renglones (una reinstalación), la sincronización lo reporta como llave repetida y NO toca VEHICULOS hasta que alguien lo resuelva.',
                '208 de 208',
            ],
            [
                'Vehículos',
                'CAMBIOS VEHICULOS — renglones con CAMPO = UBICACION',
                'Después de la limpieza #23 la columna ya no se llama así',
                'Es el historial: dice cómo se llamaba la columna cuando se hizo el cambio, y reescribirlo falsearía el registro. Consecuencia que hay que saber: desde el renombre, los cambios nuevos de ese dato se anotan como OFICINA / DESARROLLO, así que su historial queda con DOS nombres. Quien filtre Cambios Vehículos por ese dato tiene que buscar los dos.',
                '489 en producción (467 en el libro del equipo)',
            ],
        ],
    },
    {
        "nombre": 'Caja Chica — análisis',
        "anchos": [40.0, 30.0, 62.0],
        "encabezados": ['Qué se midió', 'Resultado', 'Lectura'],
        "filas": [
            [
                'Llaves únicas',
                'CAJAS CHICAS 285/285, ARQUEOS 145/145, INCREMENTOS 9/9',
                'Cero duplicados en las tres. Las llaves están sanas.',
            ],
            [
                'Integridad referencial hacia CAJAS CHICAS',
                'ARQUEOS 145/145 (100%), INCREMENTOS 9/9 (100%)',
                'Cero huérfanos. Es la ÚNICA familia de las tres con integridad perfecta.',
            ],
            [
                'El monto actual contra el log de incrementos',
                '9 de 9 coinciden',
                'CAJAS CHICAS.MONTO ACTUAL coincide con INCREMENTOS.CANTIDAD ACTUALIZADA en los 9 casos. El dato denormalizado NO se ha desviado.',
            ],
            [
                'La aritmética de cada arqueo',
                '144 de 145 cuadran',
                'DIFERENCIA = TOTAL GENERAL − MONTO CAJA en 144. La excepción es 2026_222_001, con el signo invertido.',
            ],
            [
                'Valores de relleno en el catálogo',
                'entre 2 y 12 celdas por columna',
                'Prácticamente no hay. Comparado con los 1,124 de VEHICULOS, esta familia está limpia.',
            ],
            [
                'DEPARTAMENTO contra el catálogo DEPARTAMENTOS',
                '25 de 283 fuera del catálogo',
                'El mismo problema de todo el sistema: el catálogo está desactualizado. Aquí además hay dos grafías del mismo departamento.',
            ],
            [
                'Columnas completamente vacías',
                '1 en CAJAS CHICAS, 4 en ARQUEOS',
                'CALIFICACION PROMEDIO (0 de 285) y, en ARQUEOS, TIEMPO DE ARQUEO, CANTIDAD M, CANTIDAD B y FIRMA ASISTENTE.',
            ],
            [
                'Estatus de las cajas',
                '186 CERRADA, 97 VIGENTE, 2 EN PROCESO DE CIERRE',
                'Dos terceras partes están cerradas. Importa para la app: conviene mostrar VIGENTE por omisión.',
            ],
            [
                'Forma de la familia',
                '1 catálogo + 2 bitácoras',
                'CAJAS CHICAS es el catálogo; ARQUEOS (fechado, con firmas y PDF) e INCREMENTOS (CANTIDAD ANTERIOR → ACTUALIZADA) son bitácoras. Misma forma que Vehículos y Líneas.',
            ],
        ],
    },
    {
        "nombre": 'Cómo se midió',
        "anchos": [30.0, 96.0],
        "encabezados": ['Punto', 'Detalle'],
        "filas": [
            [
                Celda('Fecha', negrita=True),
                '30/09/2026',
            ],
            [
                Celda('Libro', negrita=True),
                "Laboratorio 'Inventario Reemplazable' (1-RA6lmh-rZ-OKfsZSLl2Qd9lLyuDZ3dx3fP0M7qL-5o), que es una copia fiel de producción en estado pre-migración. Las mediciones de Vehículos y Líneas se hicieron contra producción directamente.",
            ],
            [
                Celda('Acceso', negrita=True),
                'SOLO LECTURA. Ninguna de estas mediciones escribió una celda.',
            ],
            [
                Celda('Método', negrita=True),
                'Lectura por API de Google Sheets, columna por columna, contando y cruzando llaves. No hay muestreo: todos los números son conteos completos.',
            ],
            [
                Celda('Ojo con las lecturas truncadas', negrita=True),
                'Un análisis anterior leyó solo hasta la columna BZ y 20,000 filas, y por eso dio tres conclusiones falsas. Estas mediciones leen el ancho completo de cada hoja.',
            ],
            [
                Celda('Documentos relacionados', negrita=True),
                'docs/relaciones.md (los centinelas y la regla caché/bitácora), docs/lineas-homologacion.md (el diagnóstico de Líneas), inconsistencias-vehiculos.xlsx (las 1,408 celdas de relleno, una por una).',
            ],
            [
                Celda('Lo que NO se midió', negrita=True),
                'De Caja Chica: si los datos de persona (RESPONSABLE, PUESTO, JEFE INMEDIATO) coinciden con COLABORADORES, y si los desgloses de billetes y monedas suman los totales. De Líneas: la distribución de los cambios en el tiempo.',
            ],
            [
                Celda('Estado de Líneas', negrita=True),
                'EN PAUSA. Hubo una junta del área el 30/09/2026 y se esperan cambios importantes antes de tocar nada de esa familia.',
            ],
            [
                Celda('Lo que NO se midió (actualizado)', negrita=True),
                'Ya se midieron las dos cosas que faltaban de Caja Chica: los datos de persona contra COLABORADORES y la aritmética de los arqueos. Queda pendiente de Líneas la distribución de los cambios en el tiempo.',
            ],
            [
                Celda('Un límite que hay que saber', negrita=True),
                'ARQUEOS no tiene fórmulas: sus totales son valores literales que escribió AppSheet. Eso NO impide verificarlos —cuadran los 145— pero sí significa que la fórmula vive en AppSheet y no en el spreadsheet. La que aplica la confirmó Ayrton el 30/09/2026.',
            ],
            [
                Celda('Una corrección de este archivo', negrita=True),
                'La primera versión reportó una brecha de $986,185.11 en TOTAL GENERAL. Estaba mal: sumé 11 de las 12 columnas de la fórmula y omití DISPONIBLE CUENTA BANCARIA, que suma exactamente esa cantidad. ARQUEOS cuadra al centavo en los 145 arqueos. Queda anotado para que nadie persiga un problema que no existe.',
            ],
            [
                Celda('Lineas se reestructuro el 30/09/2026', negrita=True),
                'Hubo junta del area y los cambios ya estan en el libro COMPARTIDO del equipo (1fC77Uu1...), no en produccion. Se eliminaron 4 pestañas: HISTORIAL_REASIGNACIONES, REACTIVACION DE LINEAS, SOLICITUD DE LINEAS y BITACORA DE DESECHO. Por eso las limpiezas 5, 7, 4 y 8 cambiaron de estado. Verificado despues de la reestructuracion: NUCO sigue siendo llave unica, 1,615 de 1,615. Detalle en docs/lineas-homologacion.md, en el aviso de arriba.',
            ],
            [
                Celda('Sensores ↔ VEHICULOS (01/10/2026)', negrita=True),
                "Medido en PRODUCCIÓN (1h5ibDsmVtrG27rwMaOvj-lm08QZUHzDv3woPmkfRQrk), solo lectura. Producción no tiene la columna ID, así que ahí se emparejó por SERIE VEHICULO, igual que Relaciones.gs. Resultado: 648 vehículos y 208 renglones de sensor (186 ACTIVO, 22 BAJA), con a lo más UN renglón por vehículo (208 de 208). En el libro del equipo salen además 3 casos que son datos de prueba y no existen en producción: la serie 'prueba', AUT0025 con dos sensores activos y una serie activa en otro vehículo.",
            ],
        ],
    },
    {
        "nombre": 'Caja Chica — personas',
        "anchos": [34.0, 24.0, 10.0, 9.0, 12.0, 46.0],
        "encabezados": ['Columna en CAJAS CHICAS', 'Contra COLABORADORES ACTUALIZADO', 'Coinciden', 'Difieren', '% de acuerdo', 'Lectura'],
        "filas": [
            [
                'RESPONSABLE DE CAJA CHICA',
                'NOMBRE COMPLETO',
                214,
                69,
                '76%',
                'Sobre todo acentos y nombres compuestos. La persona es la correcta.',
            ],
            [
                'DEPARTAMENTO',
                'DEPARTAMENTO',
                208,
                73,
                '74%',
                'Mismo nivel que en Líneas. Sincronizable con revisión.',
            ],
            [
                'JEFE INMEDIATO DEL REPSONSABLE',
                'JEFE DIRECTO',
                124,
                97,
                '56%',
                'Y 62 sin dato de un lado. Flojo para sincronizar.',
            ],
            [
                'OFICINA',
                'OFICINA/DESARROLLO',
                79,
                200,
                '28%',
                'Muy bajo. Probablemente miden cosas distintas.',
            ],
            [
                'SEDE',
                'SEDE',
                72,
                209,
                '26%',
                'El MISMO 26% que en Líneas. Dos familias distintas dan el mismo número, así que no es coincidencia: la sede de la caja y la sede donde trabaja la persona son cosas distintas.',
            ],
            [
                'PUESTO DE RESPONSABLE',
                'PUESTO',
                49,
                232,
                '17%',
                'El más bajo de todo el sistema. No sincronizar sin preguntar.',
            ],
            [],  # renglón vacío: separa secciones
            [
                Celda('Cómo se emparejó', negrita=True),
                None,
                'CAJAS CHICAS no tiene número de empleado. Se emparejó por CORREO ELECTRONICO DE RESPONSABLE (216 de 285, 76%) y por nombre (277, 97%); con cualquiera de las dos, 283 de 285 (99%).',
                None,
                None,
                None,
            ],
            [
                Celda('Lo bueno', negrita=True),
                None,
                'El 99% de las cajas encuentran a su responsable en el catálogo. Es la tasa más alta de las tres familias: en Líneas es 45%.',
                None,
                None,
                None,
            ],
            [
                Celda('Lo que NO se debe sincronizar', negrita=True),
                None,
                'PUESTO (17%), SEDE (26%) y OFICINA (28%). Que SEDE dé exactamente el mismo 26% que en Líneas refuerza que esa columna significa algo distinto del catálogo de personas.',
                None,
                None,
                None,
            ],
        ],
    },
    {
        "nombre": 'Caja Chica — el dinero',
        "anchos": [42.0, 26.0, 68.0],
        "encabezados": ['Qué se midió', 'Resultado', 'Lectura'],
        "filas": [
            [
                'Las columnas M 0,50 … B 1000,00: ¿piezas o importes?',
                Celda('PIEZAS, 145 de 145', negrita=True, relleno='verde'),
                'Probé las dos hipótesis. Sumadas tal cual cuadran 123 y 111 veces; multiplicadas por su denominación cuadran 145 y 145. Son conteos de piezas, sin excepción.',
            ],
            [
                'TOTAL M = suma de monedas × denominación',
                Celda('145 de 145', negrita=True, relleno='verde'),
                'Perfecto.',
            ],
            [
                'TOTAL B = suma de billetes × denominación',
                Celda('145 de 145', negrita=True, relleno='verde'),
                'Perfecto.',
            ],
            [
                'TOTAL EFECTIVO = TOTAL M + TOTAL B',
                Celda('145 de 145', negrita=True, relleno='verde'),
                'Perfecto.',
            ],
            [
                'TOTAL GENERAL = la suma de sus 12 partes',
                Celda('145 de 145  ✓', negrita=True, relleno='verde'),
                'Cuadra al centavo en los 145 arqueos, con brecha total de $0.00. La fórmula, que Ayrton verificó en AppSheet el 30/09/2026, es: TOTAL EFECTIVO + DISPONIBLE CUENTA BANCARIA + TOTAL CHEQUES + los 8 de facturas y viáticos + OTROS.',
            ],
            [
                'DIFERENCIA = TOTAL GENERAL − MONTO CAJA',
                Celda('144 de 145', negrita=True, relleno='verde'),
                'La única excepción es el arqueo 2026_222_001, con el signo invertido: dice −2.50 y debería ser +2.50. Es la limpieza #12.',
            ],
            [
                'Arqueos sin efectivo físico (TOTAL EFECTIVO = 0)',
                Celda('109 de 145', negrita=True, relleno='verde'),
                'NO es un hallazgo: el fondo de esas cajas está en una CUENTA BANCARIA, no en efectivo. DISPONIBLE CUENTA BANCARIA trae dato en 111 de los 145 arqueos y suma $986,185.11.',
            ],
            [],  # renglón vacío: separa secciones
            [
                Celda('CORRECCIÓN A UNA VERSIÓN ANTERIOR DE ESTA HOJA', negrita=True, relleno='rojo'),
                None,
                None,
            ],
            [
                Celda('Qué decía', negrita=True),
                None,
                'Que TOTAL GENERAL no cuadraba con sus partes en 111 de 145 arqueos, con una brecha acumulada de $986,185.11 «sin explicar».',
            ],
            [
                Celda('Por qué estaba mal', negrita=True),
                None,
                'Sumé 11 columnas y la fórmula tiene 12: me faltó DISPONIBLE CUENTA BANCARIA. Esa columna suma exactamente $986,185.11 — el mismo número, al centavo. La brecha era mi omisión, no un problema de los datos.',
            ],
            [
                Celda('Lo que en realidad pasa', negrita=True),
                None,
                'Muchas cajas no guardan efectivo: su fondo está en una cuenta bancaria o fintech (la hoja tiene DESCRIPCION CUENTA BANCARIA y Nombre_Fintech). Por eso TOTAL EFECTIVO = 0 en 109 arqueos, y es normal.',
            ],
            [
                Celda('Y sobre DIFERENCIA = 0', negrita=True),
                None,
                'También estaba mal dicho. Con la fórmula completa, DIFERENCIA sí es un control real: compara el total de lo que hay contra el fondo autorizado. Que valga 0 significa que la caja cuadró, no que el número esté inventado.',
            ],
        ],
    },
    {
        "nombre": 'Nombres de columnas',
        "anchos": [6.0, 11.0, 18.0, 18.0, 22.0, 34.0, 40.0, 44.0, 14.0],
        "encabezados": ['#', 'Familia', 'Hoja', 'Se llama hoy', 'Se va a llamar', 'Así se llama en', 'Por qué ese nombre', 'Qué cambia junto', 'Estado'],
        "filas": [
            [
                23,
                'Vehículos',
                'VEHICULOS',
                'UBICACION',
                'OFICINA / DESARROLLO',
                'INSTALACION DE SENSORES, INSPECCION VEHICULAR, LINEAS TELEFONICAS y sus hijas, LISTAS, DEPARTAMENTOS',
                'Es el nombre que usa el resto de la base, y la única hoja distinta era la dueña del dato. Renombrar una columna es más barato que renombrar cinco.',
                'En el mismo commit: Relaciones.MAPA, InspeccionesService.DEL_VEHICULO y el formulario de Vehículos (la etiqueta para la gente sigue siendo "Ubicación"). AppSheet: en producción ya estará apagado cuando corra el pipeline; en el libro del equipo, la app de pruebas de AppSheet deja de ver la columna hasta regenerar su esquema. El historial de CAMBIOS VEHICULOS no se toca (ver "Lo que NO se toca").',
                'PENDIENTE',
            ],
            [
                '—',
                'Líneas',
                'INSPECCIONES LINEAS, RESPONSIVAS LINEAS',
                'No TELEFONO',
                'NUMERO TELEFONO',
                'LINEAS TELEFONICAS',
                'Es el nombre que tiene en la hoja dueña (LINEAS TELEFONICAS). Medido el 01/10/2026 uniendo por ID LINEA: 74% y 85% iguales; las diferencias son la línea de hoy contra la del día del documento.',
                'Es código de Líneas (Emmanuel): LineasCaptura, LineasRepo y los formularios de inspección y responsiva buscan estas columnas por nombre. Decidir con él antes de agregarlas a MIGRACION_NOMBRES.',
                'POR DECIDIR',
            ],
            [
                '—',
                'Líneas',
                'INSPECCIONES LINEAS, RESPONSIVAS LINEAS',
                'SIM',
                'NUMERO SIM',
                'LINEAS TELEFONICAS',
                'Es el nombre que tiene en la hoja dueña (LINEAS TELEFONICAS). Medido el 01/10/2026 uniendo por ID LINEA: 84% y 93% iguales.',
                'Es código de Líneas (Emmanuel): LineasCaptura, LineasRepo y los formularios de inspección y responsiva buscan estas columnas por nombre. Decidir con él antes de agregarlas a MIGRACION_NOMBRES.',
                'POR DECIDIR',
            ],
            [
                '—',
                'Líneas',
                'INSPECCIONES LINEAS, RESPONSIVAS LINEAS',
                'CORREO',
                'CUENTA GOOGLE',
                'LINEAS TELEFONICAS',
                'Es el nombre que tiene en la hoja dueña (LINEAS TELEFONICAS). Medido el 01/10/2026 uniendo por ID LINEA: 53% y 68% iguales, y el bot ACTUALIZAR DESDE INSPECCION ya las trata como la misma columna.',
                'Es código de Líneas (Emmanuel): LineasCaptura, LineasRepo y los formularios de inspección y responsiva buscan estas columnas por nombre. Decidir con él antes de agregarlas a MIGRACION_NOMBRES.',
                'POR DECIDIR',
            ],
            [
                '—',
                'Líneas',
                'INSPECCIONES LINEAS, RESPONSIVAS LINEAS',
                'MODELO',
                'EQUIPO',
                'LINEAS TELEFONICAS',
                'Es el nombre que tiene en la hoja dueña (LINEAS TELEFONICAS). Medido el 01/10/2026 uniendo por ID LINEA: 99.7% y 99.3% iguales.',
                'Es código de Líneas (Emmanuel): LineasCaptura, LineasRepo y los formularios de inspección y responsiva buscan estas columnas por nombre. Decidir con él antes de agregarlas a MIGRACION_NOMBRES.',
                'POR DECIDIR',
            ],
            [
                '—',
                'Líneas',
                'RESPONSIVAS LINEAS',
                'No EMPLEADO',
                'NO EMPLEADO',
                'LINEAS TELEFONICAS',
                'Es el nombre que tiene en la hoja dueña (LINEAS TELEFONICAS). Medido el 01/10/2026 uniendo por ID LINEA: 66% iguales; solo cambian las mayúsculas, que para el código ya son dos columnas distintas.',
                'Es código de Líneas (Emmanuel): LineasCaptura, LineasRepo y los formularios de inspección y responsiva buscan estas columnas por nombre. Decidir con él antes de agregarlas a MIGRACION_NOMBRES.',
                'POR DECIDIR',
            ],
        ],
    },
]
